containers-ai/alameda

docs/developers.md

code-base architecture for develop k8s
Resolves #8

code-base architecture for develop k8s

---

GOVERNANCE.md

Alameda need GOVERNANCE rules for CNCF organization

Create Governance document

---

agent/exporter/prometheus/node-exporter.yaml
agent/exporter/prometheus/prometheus.yaml
agent/exporter/smart/Dockerfile
agent/exporter/smart/LICENSE
agent/exporter/smart/Makefile
agent/exporter/smart/README
agent/exporter/smart/requirements.txt
agent/exporter/smart/setup.py
agent/exporter/smart/smart_exporter/__init__.py
agent/exporter/smart/smart_exporter/__main__.py
agent/exporter/smart/smart_exporter/lib/__init__.py
agent/exporter/smart/smart_exporter/lib/pySMART/__init__.py
agent/exporter/smart/smart_exporter/lib/pySMART/attribute.py
agent/exporter/smart/smart_exporter/lib/pySMART/device.py
agent/exporter/smart/smart_exporter/lib/pySMART/device_list.py
agent/exporter/smart/smart_exporter/lib/pySMART/test_entry.py
agent/exporter/smart/smart_exporter/lib/pySMART/utils.py
agent/exporter/smart/smart_exporter/lib/smart.py
agent/exporter/smart/smart_exporter/smart_metrics.py

add smart-exporter plugin.

---

README.md

Signed-off-by: jamy.shih <jamy.shih@prophetstor.com>
issues:
#16

Add the go report card

---

agent/deploy/example/openshift-monitoring-alameda/README.md
agent/deploy/example/openshift-monitoring-alameda/influxdb.yaml
agent/deploy/example/openshift-monitoring-alameda/smart-exporter.yaml

Add yaml files that alameda needs to integrate with okd default cluster monitoring.
Resolves #27 
**Checklist:**

Add example to collect SMART data by okd default cluster monitoring.

---

operator/pkg/controller/alamedaresource/alamedaresource_controller.go
operator/pkg/utils/resources/listpods.go

add pod list in annotation of alamedaresource CR

---

operator/pkg/controller/alamedaresource/alamedaresource_controller.go

pretty print json string in annotation of AlamedaResource CR

---

operator/cmd/manager/main.go
operator/pkg/controller/alamedaresource/alamedaresource_controller.go
operator/pkg/utils/grpc/grpc.go
operator/pkg/utils/resources/listpods.go

call AI service API to register/deregister pod prediction

---

operator/Gopkg.lock
operator/cmd/manager/main.go
operator/pkg/utils/grpc/grpc.go
operator/services/grpc/config.go

allow gRPC port can be set from flag

---

operator/.dockerignore
operator/Dockerfile
operator/Makefile

update Makefile and Dockerfile

---

operator/Dockerfile

update default AI server address

---

operator/Dockerfile
operator/cmd/manager/main.go
operator/pkg/kubernetes/metrics/prometheus/prometheus.go

Read token from fixed path.

---

operator/Dockerfile
operator/Makefile

use alpine as the base image of operator

---

operator/pkg/kubernetes/metrics/prometheus/prometheus.go

Read bearer token from file that is assigned from flag.

---

operator/config/rbac/rbac_role.yaml

Update serviceaccount's permissions.

---

operator/config/rbac/rbac_role.yaml
operator/config/rbac/rbac_role_binding.yaml
operator/pkg/controller/alamedaresource/alamedaresource_controller.go

allow AlamedaResource controller to get and list pods

---

operator/pkg/kubernetes/metrics/prometheus/prometheus.go

Add default label selectors need appending while querying prometheus.

---

operator/services/grpc/service.go

return status code and message in CreatePredictResult function

---

operator/services/grpc/service.go

add empty field check for prediction data from AI server

---

operator/pkg/kubernetes/metrics/prometheus/prometheus.go
operator/pkg/kubernetes/metrics/prometheus/type.go
operator/services/grpc/validate.go

Enhance api "ListMetrics"

---

operator/services/grpc/service.go

Signed-off-by: jamy.shih <jamy.shih@prophetstor.com>
Fixed re-import package
Resolves #83

fixed re-import package(#83)

---

operator/pkg/apis/autoscaling/v1alpha1/alamedaresource_types_test.go
operator/pkg/apis/autoscaling/v1alpha1/alamedaresourceprediction_types_test.go
operator/pkg/controller/alamedaresource/alamedaresource_controller.go
operator/pkg/controller/alamedaresourceprediction/alamedaresourceprediction_controller.go
operator/pkg/utils/log/log.go

fix creating AlamedaResource does not trigger pod prediction registry

---

example/deployment/minishift/README.md

update minishift README.md

---

operator/pkg/controller/alamedaresource/alamedaresource_controller.go

initial annotation if default annotation if nil

---

operator/pkg/controller/alamedaresource/alamedaresource_controller.go

update annotation for AlamedaResource CR

---

operator/cmd/manager/main.go
operator/pkg/kubernetes/metrics/prometheus/prometheus.go
operator/services/grpc/service.go

Change log instance from log.Logger to log.Scope .
Resolves #108

Change use of log pkg

---

example/deployment/minishift/deployconfig/operator_deployconfig.yaml
operator/etc/operator.yml
operator/pkg/kubernetes/metrics/prometheus/config.go
operator/pkg/kubernetes/metrics/prometheus/prometheus.go
operator/pkg/kubernetes/metrics/prometheus/prometheus_test.go
operator/pkg/kubernetes/metrics/prometheus/type.go
operator/server/config.go
operator/server/server.go
operator/services/grpc/config.go

Add prometheus unit test and add method "Validate" of configuration structs.
Resolves #65

Add prometheus unit test

---

operator/etc/operator.yml
operator/pkg/utils/log/config.go

hide stacktrace-level log configuration as development optional setting

---

operator/cmd/manager/main.go

Signed-off-by: jamy.shih <jamy.shih@prophetstor.com>
Resolves #116

Improve the readable

---

example/deployment/minishift/README.md

Signed-off-by: Elsvent Hong <Elsvent.hong@prophetstor.com>
Resolves #

Update alameda-ai git address for minishift

---

operator/pkg/controller/alamedaresourceprediction/alamedaresourceprediction_controller.go

remove unused log print

---

operator/cmd/manager/main.go
operator/pkg/controller/alamedaresource/alamedaresource_controller.go

Retry updating alamedaresource if operation cannot be fulfilled

---

example/samples/nginx/alameda_deployment.yaml
operator/etc/operator.yml
operator/pkg/controller/alamedaresourceprediction/alamedaresourceprediction_controller.go

fix wrong deployment name in alamedaresourceprediction

---

docs/build.md
docs/deploy.md
example/deployment/openshift/README.md
example/deployment/openshift/build_config/dashboard-build.yaml
example/deployment/openshift/deployconfig/dashboard_deployconfig.yaml
example/deployment/openshift/service/dashboard_svc.yaml

update dashboard deployment configuration

---

docs/build.md
docs/deploy.md
docs/quickstart.md
example/deployment/kubernetes/3rdParty/grafana.yaml
example/deployment/kubernetes/3rdParty/prometheus.yaml
example/deployment/kubernetes/README.md
example/deployment/kubernetes/crds/autoscaling_v1alpha1_alamedaresource.yaml
example/deployment/kubernetes/crds/autoscaling_v1alpha1_alamedaresourceprediction.yaml
example/deployment/kubernetes/deployconfig/alameda-ai.yaml
example/deployment/kubernetes/deployconfig/operator.yaml
example/samples/nginx/alamedaresource.yaml
example/samples/nginx/nginx_deployment.yaml

Signed-off-by: Matt Wu <mamafun@gmail.com>

add deploy example to native kubernetes cluster

---

datahub/pkg/dao/metric/metric.go
datahub/pkg/dao/metric/prometheus/promtheusImpl.go
datahub/pkg/entity/prometheus/nodeCPUUsagePercentage/entity.go
datahub/pkg/entity/prometheus/nodeMemoryAvailableBytes/entity.go
datahub/pkg/entity/prometheus/nodeMemoryBytesTotal/entity.go
datahub/pkg/entity/prometheus/nodeMemoryUsageBytes/entity.go
datahub/pkg/repository/prometheus/metric/node_cpu_usage_percentage.go
datahub/pkg/repository/prometheus/metric/node_memory_usage_bytes.go
datahub/server.go
datahub/types.go

Implement ListNodesMetric in prometheus dao.

Implement ListNodesMetric api

---

Jenkinsfile

Signed-off-by: Elsvent Hong <Elsvent.hong@prophetstor.com>
Resolves #

Add jenkinsfile for CI

---

datahub/pkg/dao/prediction/impl/influxdbImpl.go

Add log message.

---

example/deployment/openshift/deployconfig/datahub_deployconfig.yaml
example/deployment/openshift/rbac/cluster_role.yaml
example/deployment/openshift/rbac/cluster_role_binding.yaml

Add rbac for serviceaccout datahub.
Modify datahub environment name.

Add rbac for serviceaccout datahub.

---

example/deployment/openshift/README.md
example/deployment/openshift/template/README.md
example/deployment/openshift/template/dev/alameda-ai.yml
example/deployment/openshift/template/dev/alameda-crd-rbac.yaml
example/deployment/openshift/template/dev/alameda-datahub.yml
example/deployment/openshift/template/dev/alameda-operator.yml
example/deployment/openshift/template/dev/deploy-on-openshift.sh
example/deployment/openshift/template/dev/manifests/01-namespace.yaml
example/deployment/openshift/template/dev/manifests/02-role.yaml
example/deployment/openshift/template/dev/manifests/03-role-binding.yaml
operator/Dockerfile.rhel7

Signed-off-by: jamy.shih <jamy.shih@prophetstor.com>
Resolves #241

add Openshift template for alameda installation

---

admission-controller/Dockerfile.okd.rhel7
admission-controller/Dockerfile.rhel7
evictioner/Dockerfile.okd.rhel7
evictioner/Dockerfile.rhel7
openshift/template/build/alameda-rhel7.yml
openshift/template/build/alameda.yml

Add dockerfile for rhel

---

openshift/template/deploy/alameda.yml

Signed-off-by: Hungo Hung <hungo.hung@prophetstor.com>
Resolves #

Add specify function for docker hub tag into template

---

operator/pkg/controller/alamedarecommendation/alamedarecommendation_controller.go
operator/pkg/utils/resources/list_resources.go
operator/pkg/utils/resources/resource_link.go

add nil pointer check

---

admission-controller/deployment.yaml
example/deployment/kubernetes/admission-controller/clusterrole.yaml
helm/alameda/charts/admission-controller/templates/clusterrole.yaml

fixed #458 
Resolves #
add admission-controller api-group requirements for openshift 3.9

add admission-controller api-group requirements for openshift 3.9

---

example/deployment/kubernetes/alameda-operator/crd.yaml
example/deployment/openshift/crds/autoscaling_v1alpha1_alamedascaler.yaml
example/samples/nginx/alamedascaler.yaml
helm/alameda/templates/crd.yaml
openshift/template/deploy/alameda.yml
openshift/template/dev/alameda-crd-rbac.yml
operator/config/crds/autoscaling_v1alpha1_alamedascaler.yaml
operator/config/samples/alameda_deployment.yaml
operator/pkg/apis/autoscaling/v1alpha1/alamedascaler_types.go
operator/pkg/controller/alamedascaler/alamedascaler_controller.go

 Add scalingTool

---

design/crd_alamedascaler.md
example/deployment/kubernetes/alameda-operator/crd.yaml
example/deployment/openshift/crds/autoscaling_v1alpha1_alamedascaler.yaml
example/samples/nginx/alamedascaler.yaml
helm/alameda/templates/crd.yaml
openshift/template/deploy/alameda.yml
openshift/template/dev/alameda-crd-rbac.yml
operator/config/crds/autoscaling_v1alpha1_alamedascaler.yaml
operator/config/samples/alameda_deployment.yaml
operator/pkg/apis/autoscaling/v1alpha1/alamedascaler_types.go

[CRD] change key names in AlamedaScaler CRD to camel case
Signed-off-by: Matt Wu <matt.wu@prophetstor.com>

[CRD] change key names in AlamedaScaler CRD to camel case

---

datahub/pkg/entity/influxdb/utils/enumconv/top_controller.go

Signed-off-by: link.hsieh <link.hsieh@prophetstor.com>
(cherry picked from commit 481c38276c012a975729019c0e9db2540b8a6add)
Signed-off-by: link.hsieh <link.hsieh@prophetstor.com>
Resolves #

[datahub] Add StatefulSet to enumconv.

---

datahub/etc/datahub.toml

[datapipe] Add rabbitmq configuration in datahub.toml file

---

grafana/rootfs/usr/share/grafana/public/dashboards/home.json

Signed-off-by: henman.chen <henman.chen@prophetstor.com>

add license expired time and license status on dashboard

---

grafana/rootfs/etc/grafana/provisioning/dashboards/dashboardproviders.yaml
grafana/rootfs/var/lib/grafana/dashboards/Cost/cost-analysis.json

Signed-off-by: henman.chen <henman.chen@prophetstor.com>

Add Cost folder and cost-analysis.json

---

grafana/rootfs/var/lib/grafana/dashboards/Insight/cluster-gpu-info.json
grafana/rootfs/var/lib/grafana/dashboards/Insight/gpu-for-node.json

Add GPU monitoring page in Insight folder

Add GPU monitoring page in Insight folder

---

grafana/rootfs/var/lib/grafana/dashboards/Recommendation/vpa-recommendation.json

Hide upper bound and lower bound on VPA Recommendataion

Hide upper bound and lower bound on VPA Recommendataion

---

grafana/rootfs/var/lib/grafana/dashboards/Cost/cost-analysis.json

Init cost-analysis for NKS meeting

Init cost-analysis for NKS meeting

---

notifier/etc/notifier.yml

Signed-off-by: ytliu <yungtsun.liu@prophetstor.com>
Resolves #

[notifier] add event type "License"

---

grafana/rootfs/var/lib/grafana/dashboards/Recommendation/vpa-recommendation-alamedascaler.json
grafana/rootfs/var/lib/grafana/dashboards/Recommendation/vpa-recommendation-cluster.json
grafana/rootfs/var/lib/grafana/dashboards/Recommendation/vpa-recommendation-namespace.json
grafana/rootfs/var/lib/grafana/dashboards/Recommendation/vpa-recommendation.json

Change Memory size unit from decbytes to bytes

---

grafana/rootfs/var/lib/grafana/dashboards/Insight/cluster-gpu-info.json

Need to be Selected datasource for showing GPU

---

grafana/rootfs/var/lib/grafana/dashboards/Home/home.json
grafana/rootfs/var/lib/grafana/dashboards/Planning/prediction-1day.json

(1)Change row style on home dashboard 
(2)Remove past data of cpu and memory recommendation on prediction page

Change style on home dashboard and remove past data of cpu and memory recommendation on prediction page

---

datahub/pkg/entity/influxdb/cluster_status/container.go
datahub/pkg/repository/influxdb/cluster_status/container.go

(cherry picked from commit 9bf2a65cf5ca994805c13518c50d44e1198ad2d8)

[datahub] Bug 44 fix, HPA recommendation CPU/Memory limit are not matched with desired replica * cpu/memory limit

---

grafana/init.sh

Signed-off-by: Hungo Hung <hungo.hung@prophetstor.com>
Resolves #

Delete all files to force grafana reset

---

grafana/rootfs/var/lib/grafana/dashboards/Cost/cost-analysis.json

Signed-off-by: henman.chen <henman.chen@prophetstor.com>

setr decimal to 2 for current_cost.

---

ai-dispatcher/pkg/dispatcher/measure.go

drift if MAPE or RMSE calculate failed

---

datahub/pkg/dao/entities/influxdb/clusterstatus/container.go
datahub/pkg/dao/entities/influxdb/clusterstatus/pod.go
datahub/pkg/dao/interfaces/clusterstatus/types/container.go
datahub/pkg/dao/interfaces/clusterstatus/types/pod.go
datahub/pkg/dao/repositories/influxdb/clusterstatus/container.go
datahub/pkg/dao/repositories/influxdb/clusterstatus/pod.go

[datahub] Refine data format conversion methods of pod & container

---

Gopkg.lock
Gopkg.toml

[datahub] Remove prototype constraint in Gopkg.toml

---

datahub/pkg/dao/entities/influxdb/predictions/application.go
datahub/pkg/dao/entities/influxdb/predictions/cluster.go
datahub/pkg/dao/entities/influxdb/predictions/container.go
datahub/pkg/dao/entities/influxdb/predictions/controller.go
datahub/pkg/dao/entities/influxdb/predictions/namespace.go
datahub/pkg/dao/entities/influxdb/predictions/node.go
datahub/pkg/dao/interfaces/predictions/influxdb/pod.go
datahub/pkg/dao/interfaces/predictions/types/container.go
datahub/pkg/dao/interfaces/predictions/types/controller.go
datahub/pkg/dao/repositories/influxdb/predictions/application.go
datahub/pkg/dao/repositories/influxdb/predictions/cluster.go
datahub/pkg/dao/repositories/influxdb/predictions/container.go
datahub/pkg/dao/repositories/influxdb/predictions/controller.go
datahub/pkg/dao/repositories/influxdb/predictions/namespace.go
datahub/pkg/dao/repositories/influxdb/predictions/node.go
datahub/pkg/formatconversion/requests/clusterstatus-metadata.go
datahub/pkg/formatconversion/requests/predictions-app.go
datahub/pkg/formatconversion/requests/predictions-controller.go
datahub/pkg/formatconversion/requests/predictions-namespace.go
datahub/pkg/formatconversion/requests/predictions-node.go
datahub/pkg/formatconversion/requests/predictions-pod.go
datahub/pkg/formatconversion/responses/predictions-controller.go
datahub/pkg/kubernetes/metadata/metadata.go

[datahub] Fix bug that prediction APIs does not work properly with parameter granularity

---

example/samples/nginx/alamedadetection.yaml

Signed-off-by: Shenglin Wu <shenglin.wu@prophetstor.com>
Resolves #

Fix AlamedaDetection sample yaml indent

---

datahub/pkg/apis/v1alpha1/resources-app.go
datahub/pkg/apis/v1alpha1/resources-cluster.go
datahub/pkg/apis/v1alpha1/resources-controller.go
datahub/pkg/apis/v1alpha1/resources-namespace.go
datahub/pkg/apis/v1alpha1/resources-node.go
datahub/pkg/apis/v1alpha1/resources-pod.go
datahub/pkg/dao/interfaces/clusterstatus/influxdb/pod.go

[datahub] Check if list is empty before creating resources

---

ai-dispatcher/pkg/dispatcher/application_model_job_sender.go
ai-dispatcher/pkg/dispatcher/cluster_model_job_sender.go
ai-dispatcher/pkg/dispatcher/controller_model_job_sender.go
ai-dispatcher/pkg/dispatcher/gpu_model_job_sender.go
ai-dispatcher/pkg/dispatcher/namespace_model_job_sender.go
ai-dispatcher/pkg/dispatcher/node_model_job_sender.go
ai-dispatcher/pkg/dispatcher/pod_model_job_sender.go

Add WaitGroup for wait goroutine

---

ai-dispatcher/pkg/dispatcher/application_model_job_sender.go
ai-dispatcher/pkg/dispatcher/cluster_model_job_sender.go
ai-dispatcher/pkg/dispatcher/controller_model_job_sender.go
ai-dispatcher/pkg/dispatcher/gpu_model_job_sender.go
ai-dispatcher/pkg/dispatcher/namespace_model_job_sender.go
ai-dispatcher/pkg/dispatcher/node_model_job_sender.go
ai-dispatcher/pkg/dispatcher/pod_model_job_sender.go

remove goroutine

---

ai-dispatcher/cmd/app/probe.go
ai-dispatcher/pkg/dispatcher/application_model_job_sender.go
ai-dispatcher/pkg/dispatcher/cluster_model_job_sender.go
ai-dispatcher/pkg/dispatcher/controller_model_job_sender.go
ai-dispatcher/pkg/dispatcher/gpu_model_job_sender.go
ai-dispatcher/pkg/dispatcher/namespace_model_job_sender.go
ai-dispatcher/pkg/dispatcher/node_model_job_sender.go
ai-dispatcher/pkg/dispatcher/pod_model_job_sender.go
ai-dispatcher/pkg/probe/liveness_probe.go
ai-dispatcher/pkg/probe/probe.go

Kroos rhmp

---

admission-controller/pkg/probe/readiness_probe.go
ai-dispatcher/pkg/probe/liveness_probe.go
ai-dispatcher/pkg/probe/readiness_probe.go
datahub/pkg/probe/liveness.go
evictioner/pkg/probe/readiness_probe.go
operator/pkg/probe/readiness_probe.go
rabbitmq/cmd/app/probcheck.go

check connection is not nil before closing them
